name: Setup Node
description: Setup Node.js, install dependencies

runs:
  using: composite
  steps:
    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version

    - name: Install dependencies
      run: yarn install --no-immutable
      shell: bash
      env:
        YARN_ENABLE_HARDENED_MODE: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork && '1' || '0' }}
