name: reviewdog

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  biome:
    name: biome
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node

      - uses: mongolyy/reviewdog-action-biome@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

  typecheck:
    name: typecheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node
      - uses: EPMatt/reviewdog-action-tsc@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
