name: reviewdog

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  biome:
    name: biome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-reviewdog

      - name: Run biome with reviewdog
        run: yarn lint --reporter=json | reviewdog -f=biome -reporter=github-pr-review -level=notice
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  typecheck:
    name: typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-reviewdog

      - name: Run typecheck with reviewdog
        run: yarn typecheck 2>&1 | reviewdog -f=gcc -name=typecheck -reporter=github-pr-review -level=warning
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
